## 2. Matrizes especiais e determinante

Matrizes especiais são matrizes que possuem propriedades ou características específicas que as distinguem de matrizes comuns. Essas propriedades especiais podem ser úteis em várias aplicações matemáticas, científicas e de engenharia. Algumas das matrizes especiais mais comuns incluem:

- **Matriz Identidade:** $I_{n \times n}=[\delta_{ij}]$ com $\delta_{ij}=1$ se $i=j$ e $\delta_{ij}=0$ se $i \neq j$. 


- **Matriz Diagonal:** $A_{n \times n}=[a_{ij}]$ com $a_{ij} = 0$ sempre que $i \neq j$.


- **Matriz Triangular Superior:** $A_{n \times n}=[a_{ij}]$ em que $a_{ij} = 0$ sempre que $i>j$.


- **Matriz Triangular Inferior:** $A_{n \times n}=[a_{ij}]$ em que $a_{ij} = 0$ sempre que $i<j$.


- **Matriz Simétrica:** Uma matriz $A$ é simetrica se e somente se $A^T = A$.


- **Matriz Inversa:** Uma matriz $B$ é a matriz inversa de $A$ se $BA=AB=I$. A matriz inversa de $A$ é geralmente denotada por $A^{-1}$ 


- **Matriz Ortogonal:** Uma matriz cujas colunas são ortonormais (ou seja, possuem norma 1 e são mutuamente perpendiculares). A sua matriz transposta é também a sua inversa.


- **Matriz de Vandermonde:** Uma matriz em que cada linha é uma *sequência geométrica* da linha anterior, muitas vezes usada em interpolação polinomial.


O **determinante** de uma matriz é um valor único associado a uma matriz quadrada e pode ser calculado de várias maneiras, dependendo do tamanho da matriz.

O determinante de uma matriz $A$ de ordem $n \times n $ pode ser calculado usando a expansão em cofatores:

$$\det(A) = \sum_{j=1}^{n} a_{ij} \cdot C_{ij} = a_{i1} \cdot C_{i1} + a_{i2} \cdot C_{i2} + \ldots + a_{in} \cdot C_{in}$$

onde $ a_{ij} $ é o elemento da $ i $-ésima linha e $ j $-ésima coluna de $ A $, e $ C_{ij} $ é o cofator associado ao elemento $ a_{ij} $

$$ C_{ij} = (-1)^{i+j} \cdot \det(M_{ij})$$

onde $ M_{ij} $ é a matriz obtida removendo a $i$-ésima linha e a $j$-ésima coluna de $A$.



A seguir vamos ver alguns exemplos de como criar e operar matrizes com `numpy`.

In [5]:
# importando
import numpy as np

**Exemplo 1:** É fácil criar uma matriz identidade, de ordem 3, veja o código a seguir:

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# ou, então
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Atividade:** Crie uma matriz $A_{n\times n}$ qualquer e um vetor $v$ e verifique que $A \times I = I \times A = A$ e também que $I \times v = v$, desde que as operações de multiplicação estejam definidas ($I$ e $v$ com ordem $n$).

In [31]:
# Cole e/ou escreva seu código aqui

**Exemplo 2:** funções `np.tril`, `np.triu` e `np.diag` podem ser usadas para extratir uma matriz triangular inferior e uma matriz triagular superior de uma matriz quadrada dada. Veja o exemplo a seguir:
$$
A = \begin{bmatrix}
    0.6711 & -0.1924 & 0.7163 \\
    0.1924 & 0.9631 & 0.1924 \\
   -0.7163 & 0.1924 & 0.6711
\end{bmatrix}
$$

In [32]:
A = np.array([[0.6711, -0.1924, 0.7163],
              [0.1924, 0.9631, 0.1924],
              [-0.7163, 0.1924, 0.6711]])

print (A)

[[ 0.6711 -0.1924  0.7163]
 [ 0.1924  0.9631  0.1924]
 [-0.7163  0.1924  0.6711]]


In [33]:
np.tril(A)

array([[ 0.6711,  0.    ,  0.    ],
       [ 0.1924,  0.9631,  0.    ],
       [-0.7163,  0.1924,  0.6711]])

In [34]:
np.triu(A)

array([[ 0.6711, -0.1924,  0.7163],
       [ 0.    ,  0.9631,  0.1924],
       [ 0.    ,  0.    ,  0.6711]])

In [35]:
# extraindo a diagonal
d = np.diag(A)
print(d)

[0.6711 0.9631 0.6711]


In [36]:
# criando uma matriz diagonal
np.diag(d)

array([[0.6711, 0.    , 0.    ],
       [0.    , 0.9631, 0.    ],
       [0.    , 0.    , 0.6711]])

**Exemplo 4:** Vamos verificar se a matriz $A$ do Exemplo 2 é simétrica. 

In [37]:
A.T

array([[ 0.6711,  0.1924, -0.7163],
       [-0.1924,  0.9631,  0.1924],
       [ 0.7163,  0.1924,  0.6711]])

Não é simétrica pois $A^T \neq A$.

In [38]:
A.T==A

array([[ True, False, False],
       [False,  True,  True],
       [False,  True,  True]])

**Atividade:** Crie uma matriz qualquer $A$ e verifique se $(A^T)^T =A$

In [39]:
# Cole e/ou escreva seu código aqui

**Exemplo 5:** Vamos obter a inversa de $A$ e verificar se $A^{-1}A=AA^{-1}=I$. 

In [40]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.62115739,  0.27212218, -0.74100931],
       [-0.27212218,  0.98218044,  0.00886545],
       [ 0.74100931,  0.00886545,  0.69663138]])

In [41]:
A@Ainv

array([[ 1.00000000e+00, -1.23708264e-17,  1.16162798e-17],
       [ 3.05418100e-17,  1.00000000e+00, -2.07374958e-17],
       [-4.77414439e-17, -5.93446459e-18,  1.00000000e+00]])

Isso ficou um pouco estranho. Melhor arredondar...

In [42]:
np.round(A@Ainv)

array([[ 1., -0.,  0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

In [43]:
Ainv@A

array([[ 1.00000000e+00, -3.05418100e-17,  4.77414439e-17],
       [ 2.47966507e-17,  1.00000000e+00, -1.75761938e-17],
       [-1.16162798e-17,  7.01807977e-18,  1.00000000e+00]])

Para ficar perfeito vamos tomar o valor absoluto

In [44]:
abs(np.round(Ainv@A))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Agora sim!

**Atividade:** Calcula o determinante de $A$ e, então, tente obter a inversa $A^{-1}$, sendo

$$
A = \begin{bmatrix}
    1 & 2& -3 \\
    -1& 1 & -2 \\
    1 & 5 & -8
\end{bmatrix}
$$

Você notou que a terceira linha é igual à primeira multiplicada por 2 somada à segunda linha?

In [30]:
# Cole e/ou escreva seu código aqui

**Exemplo 6:** Verificar se a matriz $A$ do Exemplo 2 é uma matriz ortogonal.

In [16]:
# extraindo as colunas de A
c1 = A[:,0]
c2 = A[:,1]
c3 = A[:,2]

print (c1)
print (c2)
print (c3)

[ 0.6711  0.1924 -0.7163]
[-0.1924  0.9631  0.1924]
[0.7163 0.1924 0.6711]


In [17]:
#norma das colunas de A
n1 = np.linalg.norm(c1,ord=2)
n2 = np.linalg.norm(c2,ord=2)
n3 = np.linalg.norm(c3,ord=2)

print (np.round(n1,2))
print (np.round(n2,2))
print (np.round(n3,2))

1.0
1.0
1.0


**Atividade** Verifique se a matriz $N$ abaixo é ortogonal

$$N=\frac 1{\sqrt{6}}\begin{pmatrix} \sqrt{2} & 1 & \sqrt{3} \\ -\sqrt{2} & 2 & 0 \\ \sqrt{2} & 1 & -\sqrt{3} \end{pmatrix}$$

Verifique se o produto interno entre duas colunas quaisquer é igual a zero.

In [46]:
# Cole e/ou escreva seu código aqui

**Exemplo 7:** Um exemplo e uma matriz de  Vandermonde é
$$
M = \begin{bmatrix}
1 & x_1 & x_1^2 \\
1 & x_2 & x_2^2 \\
1 & x_3 & x_3^2 \\
\end{bmatrix}
= \begin{bmatrix}
1 & 2 & 4 \\
1 & 3 & 9 \\
1 & 4 & 16 \\
\end{bmatrix}
$$

Podemos criar uma matriz assim com essa usando `numpy` como é mostrado a seguir.

In [47]:
x = np.array([2,3,4])
M = np.array([x**0, x**1, x**2]).T
print (M)

[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


**Exemplo 8:** Vamos calcular o determinante das matrizes $A$ e $M$.

In [48]:
np.linalg.det(A)

0.9809408357660001

É possível provar que o determinante de uma matriz ortogonal é igual a $1$, mas devido a limitações na representação interna de números com muitas casas decimais no computador, o resultado não é exato.

In [49]:
np.linalg.det(M)

2.0

### Atividades:
**1.** Crie três matrizes $3\times 3$ diferentes $A$, $B$ e $C$ e verique que:

a) $(AB^{-1})=A^{-1}B^{-1}$

b) $\det(B^T) = det(B)$

c) $\det(kA)=k^3\det(A)$

d) $\det(AB)=\det(A)\det(B)$

e) Se $\det(A) \neq 0$ , então, $\det(A^{-1})=\frac{1}{\det(A)}$. Verifique.

f) Repita a verificação da letra e para as matrizes $B$ e $C$


**2.** Calcule o determinante da matriz 

$$A = \begin{bmatrix}
    \frac{\sqrt{2}}{2} & -\frac{\sqrt{2}}{2} \\
    \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2}
\end{bmatrix}$$

Esta é uma matriz ortogonal?