## Sistemas lineares
### Métodos diretos

É comum em computação numérica escalonar uma matriz que representa um sistema linear com o objetivo de obter um ou mais sistemas triangulares durante o processo de resolução. Sistemas lineares triangulares são aqueles cuja matriz dos coeficientes é uma matriz triangular e o algoritmo para sua resolução é bastante simples, consiste=indo de substituições subsequentes. 

Um **sistema triangular inferior** representado por $Lx=b$, possui matriz de coeficientes tal que $[l_{ij}]=0$ para $i<j$, com $i,j=0,1,...,n$. 

Um algoritmo para obter a sua solução é dado por:

$$ x_1 = b_1/a_{11}$$

para $i=2,3...,n$, faça

$$ x_i = \frac{b_i- \sum\limits_{j=1}^{(i-1)} a_{ij}x_j}{a_{ii}}$$	         
	         
Usando Python, um código que implementa esse algoritmo, é mostrado no exemplo abaixo.

### Exemplo

Seja o sistema linear
$$ \begin{cases} 
	         2x_1 = 2\\ 
             x_1 + 4x_2 = -3\\
             x_1 + x_2 + x_3 = 0
             \end{cases} $$
um código em Python que implementa esse algoritmo e a solução obtida executando o programa são mostrados a seguir 

In [31]:
import numpy as np

In [32]:
def solve_L(A,b):
    x1 = b[0]/A[0][0]
    x = [x1]

    for i in range(1,len(A)):
        soma = 0
        for j in range(0,i):
            soma +=  A[i][j]*x[j]
        x.append((b[i]-soma)/A[i][i])
    return x


In [33]:
A = np.array([[2,0,0], 
              [1,4,0], 
              [1,1,1]], dtype=np.float64) 
b = np.array([2,-3,0], dtype=np.float64) 

In [34]:
x = solve_L(A,b)
x

[1.0, -1.0, 0.0]

Ou, de modo mais elegante:


In [35]:
x = np.zeros(len(b))
for i in range(len(A)):
    x[i] = (b[i]-A[i,:i].dot(x[:i]))/A[i,i]
print (x)

[ 1. -1.  0.]


In [36]:
def solve_L(L,b): 
    x = np.zeros(len(b))
    for i in range(len(b)):
        x[i] = (b[i]-L[i,:i].dot(x[:i]))/L[i,i]
    return (x)

x = solve_L(A,b)
print(x)


[ 1. -1.  0.]


In [37]:
x = solve_L(A,b)
x

array([ 1., -1.,  0.])

In [38]:
A@x

array([ 2., -3.,  0.])

Um **sistema triangular superior** representado por $Ux=b$, possui matriz de coeficientes tal que $[u_{ij}]=0$ para $i>j$, com $i,j=0,1,...,n$. 

Um algoritmo para obter a sua solução é dado por:

$$ x_n = b_n/a_{nn}$$

para $i=(n-1), (n-2),...,1$, faça

$$ x_i = \frac{b_i- \sum\limits_{j=i+1}^{(n)} a_{ij}x_j}{a_{ii}}$$	

Usando Python, um código que implementa esse algoritmo, é mostrado abaixo.

### Exemplo
Seja o sistema linear
$$ \begin{cases} 
	         3x_1 + x_2 +x_3= 4\\ 
             2x_2 -x_3 = 2\\
             3x_3 = 3
             \end{cases} $$
             
um código em Python que implementa esse algoritmo e a solução obtida executando o programa são mostrados a seguir 

In [23]:
import numpy as np

In [24]:
A = np.array([[3,1,1], [0,2,-1], [0,0,3]]) 
b = np.array([4,2,3])

In [26]:
def solve_U(U,b):
    x = np.zeros(len(b))
    for i in range(len(b)-1,-1,-1):
        x[i]=(b[i]-np.dot(U[i,i+1:],x[i+1:]))/U[i,i]
    return (x)

x = solve_U(A,b)
print (x)

[0.5 1.5 1. ]


In [27]:
np.linalg.solve(A,b)

array([0.5, 1.5, 1. ])

Verificando a solução

In [28]:
A@x

array([4., 2., 3.])

### Fatoração LU
Uma forma de obter a fatoração $LU$ da matriz $A$, conhecido como processo Redução de Doolittle será apresentado a seguir. Considere a fatoração da matriz $A = (a_{ij})_{i,j=1,...,n}$ nas matrizes $L = (l_{ij})_{i,j=1,...,n}$ e $U = (u_{ij})_{i,j=1,...,n}$ como é mostrado a seguir

$$\left[\begin{array}{cccc} 
	         1      & 0      & \cdots & 0      \\ 
	         l_{21} & 1      & \cdots & 0      \\
	         \vdots & \vdots & \vdots & \vdots \\
	         l_{n1} & l_{n2} & \cdots & 1 \\
	         \end{array} \right] 
\left[\begin{array}{cccc} 
	         u_{11} & u_{12} & \cdots & u_{1n} \\ 
	         0      & u_{22} & \cdots & u_{2n} \\
	         \vdots & \vdots & \vdots & \vdots \\
	         0      & 0      & \cdots & u_{nn} \\
	         \end{array} \right]
	         =
\left[\begin{array}{cccc} 
	         a_{11} & a_{12} & \cdots & a_{1n} \\ 
	         a_{21} & a_{22} & \cdots & a_{2n} \\
	         \vdots & \vdots & \vdots & \vdots \\
	         a_{n1} & a_{n2} & \cdots & a_{nn} \\
	         \end{array} \right]$$

o processo de múltiplicação de matrizes nos leva às seguintes equações, que fornecem a primeira linha da matriz $U$: $u_{11}=a_{11}$, $u_{12}=a_{12}$, $u_{12}=a_{12}$,..., $u_{1n}=a_{1n}$. Seguindo o procedimento de multiplicar matrizes, podemos encontrar a 1ª coluna da matriz $L$: $l_{21}=a_{21}/u_{11}$, $l_{31}=a_{31}/u_{11}$,..., $u_{n1}=a_{n1}/u_{11}$. Continuando o processo para a 2ª linha de $U$, 2ª coluna de $L$, 3ª linha de $U$, 3ª coluna de $L$, e assim por diante, chegamos nas seguintes fórmulas:
$$u_{ij}=a_{ij}-\sum\limits_{k=1}^{i-1}l_{ik}u_{kj} \qquad i,j=1,...,n$$
e
$$l_{ij}=\frac{a_{ij}-\sum\limits_{k=1}^{j-1}l_{ik}u_{kj}}{ujj} \qquad i,j=1,...,n$$

In [24]:
def fatoracao_LU(A):
    n = len(A)     
    U = np.zeros((n,n))
    L = np.identity(n)
    for m in range(n):
        for j in range(m, n):
            U[m,j] = A[m,j] - np.sum(L[m,0:m] * U[0:m,j])
        for i in range(m+1, n):
            L[i,m] = (A[i,m] - np.sum(L[i,0:m] * U[0:m,m]))/U[m,m]
    return L,U

In [25]:
A = np.array([[2,0,1],
              [0,2,1],
              [1,1,3]])
b = np.array([3,3,5])
L,U = fatoracao_LU(A)

print ("Matriz L:")
print (np.array(L))
print ("Matriz U:")
print(np.array(U))

Matriz L:
[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.5 0.5 1. ]]
Matriz U:
[[2. 0. 1.]
 [0. 2. 1.]
 [0. 0. 2.]]


In [26]:
np.linalg.solve(L,b)


array([3., 3., 2.])

In [29]:
def solve_L(A,b):
    x1 = b[0]/A[0][0]
    x = [x1]

    for i in range(1,len(A)):
        soma = 0
        for j in range(0,i):
            soma +=  A[i][j]*x[j]
        x.append((b[i]-soma)/A[i][i])
    return x

y = solve_L(L,b)
y

[3.0, 3.0, 2.0]

In [30]:
solve_U(U,y)

array([1., 1., 1.])

Outro exemplo

In [ ]:
A = np.array([[3,2,4],
              [1,1,2],
              [4,3,2]])
b = [1,2,3]
L,U = fatoracao_LU(A)

y = solve_L(L,b)
print("y=",np.round(y,4))
x = solve_U(U,y)
print("x=",np.round(x,4))

### Método da Eliminação de Gauss

Os métodos diretos de eliminação consistem no processo 
de transformar um sistema de equações lineares $Ax=b$, em que $A= [a_{ij}]_i,j=1,..,n$, 
$x=[x_1,x_2,...,x_n]^t$ e $b=[b_1, b_2,...,b_n]^t$, em um sistema equivalente, 
aplicando operações elementares sobre as linhas da matriz aumentada $[A \mid b]$. O sistema equivalente obtido ao final do processo, deve ser de 
resolução mais simples ou imediata, por substituição direta. No caso da eliminação de Gauss 
com pivoteamento diagonal ou pivoteamento parcial, obtém-se um sistema equivalente 
na forma triangular. 

### Exemplo 
Um exemplo de algoritmo para resolver sistemas lineares por eliminação de Gauss.

In [ ]:
A = np.array([[3.,2.,4.],
              [1.,1.,2.],import scipy
import scipy.linalg
              [-4.,3.,2.]])

b = np.array([1.,2.,3.])

M = np.hstack((A,b.reshape(3,1)))
M

In [ ]:
# funcao que triangulariza o sistema
def triangulariza(M):
    n = len(M)
    for j in range(n-1):
        for i in range(j,n-1):
            m = M[i+1,j]/M[j,j]
            M[i+1] = M[i+1]-m*M[j]
    return (M)

T = triangulariza(M)
T

In [ ]:
U = T[:,0:-1]
y = T[:,-1]

In [ ]:
U

In [ ]:
def solve_trang_sup(M,m):
    M = np.flip(M)
    m = np.flip(m)
    
    for i in range(len(M)):
        m[i] = (m[i]-M[i,:i].dot(m[:i]))/M[i,i]
    return (np.flip(m))

In [ ]:
x = solve_trang_sup(U,y)
print(x)

In [ ]:
A

Verificando

In [ ]:
A.dot(x)

#### Método por inversão de matrizes

Considere o sistema de $n$ equações e $n$ variáveis dado por 

$$ Ax=b$$

Se a matriz $A$ dos coeficientes for não singular, ou seja, se o sistema possuir solução única a matriz é invertível e a solução do sistema pode ser obtida multiplicando-se a inversa $A^{-1}$ à esquerda de ambos os lados da equação, como segue: 

$$A^{-1}Ax=A^{-1}b$$
logo
$$Ix = A^{-1}b$$
ou
$$x = A^{-1}b$$
Que é a solução do sistema linear.

**Exemplo:** Resolver o sistema $Ax=b$ com $A = 
 \left[\begin{array}{ccc} 
	         3 & 0 & 1 \\ 
	         3 & 2 & 1 \\
            -3 & 1 & 3 \\
	     \end{array} \right]$
e $b = (1,1,3)^t$.    

In [ ]:
import numpy as np
from numpy.linalg import inv

A = np.array([[3,0,1],[3,2,1],[-3,1,3]])
b = np.array([1,1,3])
x = np.dot(inv(A),b)
print (np.round(x,4))

A obtenção inversa pode ser feita pelo processo de eliminação de Gauss-Jordan em que são realizadas operações elementares sobre as linhas da matriz $A$ até que ela se torne uma matriz identidade. Essas mesmas operações são realizadas em uma matriz identidade de mesma ordem, ao final das operações na matriz identidade o resultado é a inversa da matriz $A$. O exemplo a seguir implementa o processo de eliminação de Gauss-Jordan.

**Exemplo 7.12:** Vamos nesse exemplo utilizar o processo de eliminação de Gauss-Jordan para obter a matriz inversa de 
$A = 
 \left[\begin{array}{ccc} 
	         2 & 1 & 3 \\ 
	         0 & -1 & 1 \\
            1 & 0 & 3 \\
	     \end{array} \right]$

In [ ]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

A = np.array([[2,1,3],[0,-1,1],[1,0,3]], float)
I = np.identity(len(A))
M = np.concatenate((A,I), axis=1)

print ('Matriz ampliada:')
print (M)

print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (Mgj )

print ('Matriz inversa:')
Ainv = Mgj[:,3:6]
print(Ainv)

### Usando o módulo `linalg`


**Exemplo 2.4, p.33**

In [ ]:
import scipy
import scipy.linalg

In [ ]:
A = np.array([[2,0,1],
              [0,2,1],
              [1,1,3]])

In [ ]:
scipy.linalg.lu(A)

**Exemplo 2.8, p.39**


In [ ]:
A = np.array([[1,2,4],[2,8,10],[4,10,26]])
b = np.array([1,-4,10])

In [ ]:
R = np.linalg.cholesky(A)
R

In [ ]:
R@R.T

### Exercício

Obtenha, caso exista, a solução para os seguintes sistemas lineares utilizando os métodos estudados. 


a) $\begin{cases} 
	         2x_1 + 3x_2 + x_3 +5x_4= 11\\ 
	         x_1  + 3.5x_2  + x_3 +7.5x_4= 13\\
	         1.4x_1 + 2.7x_2 + 5.5x_3 + 12x_4 = 21.6\\
	         -2x_1 + 1x_2 + 3x_3 +28x_4 = 30
	         \end{cases}$
    
b) $\begin{cases} 
	         6.1x_1 + 0.32x_2 + 1.3x_3 +2.1x_4 + 0.11x_5 = 19.52\\ 
	         0.82x_1  + 8.81x_2  + 1.01x_3 +3x_4 + 3.12x_5= 15.83\\
	         0.5x_1 + 1.78x_2 + 15.2x_3 + 4.2x_4 +8.1x_5= -22.14\\
	         4.2x_1 + 5.3x_2 + 1.8x_3 +20.9x_4 +7.51x_5 = 27.28\\
	         0.2x_1 + 9.1x_2 + 4.68x_3 +4.3x_4 +20.1x_5  = -21.78
	         \end{cases}$
             
c)$ \begin{cases} 
    12.1756 x_1 + 4.0231 x_2 - 2.1732 x_3 + 5.1967 x_4 = 17.1020\\ 
   -4.0231 x_1 + 6.0030 x_2              + 1.1973 x_4 = -6.1593\\
   -1.0000 x_1 - 5.2107 x_2 + 11.1111 x_3              =  3.0004\\
	6.0235 x_1 + 7.0000 x_2 +            - 14.1561 x_4 =  0.0000
\end{cases} $

### Atividade:

Resolver os sistemas acima, por:

a) Eliminação de Gauss

b) Decomposição LU

c) Eliminação de Gauss-Jordan

d) Matriz inversa

In [ ]:
A = np.array([[6.1, 0.32, 1.3, 2.1, 0.11], 
              [0.82, 8.81, 1.01, 3, 3.12],
              [0.5, 1.78, 15.2, 4.2, 8.1],
              [4.2, 5.3, 1.8, 20.9, 7.51],
              [0.2, 9.1, 4.68, 4.3, 20.1]]) 

b = np.array([19.52, 15.83, -22.14, 27.28, -21.78])