## Sistemas lineares

### Métodos iterativos

Os métodos iterativos são indicados para sistemas de grande porte com matriz dos coeficientes esparsa, ou seja, com grande grande quantidade de zeros. Nesses casos os métodos iterativos são mais rápidos e demandam menos memória para armazenamento, além disso, possuem a vantagem de se auto corrigirem se erro é cometido. Podem ser usados para reduzir os erros de arredondamento na solução obtida por métodos exatos. Além disso, sob certas condições, podem resolver um conjunto de equações não lineares. No entando para serem convergentes precisam atender a certas condições. Dizemos que a sequência de vetores $x^{(k)}$, $k=0,1,2,..$ de um espaço vetorial $V$ converge para a solução exata $\bar{x} \in V$ se $\|x^{(k)} - \bar{x}\|  \rightarrow 0$, quando $k \rightarrow \infty$ para alguma norma $ \| \cdot \|$ sobre o espaço vetorial $V$.

**Exemplo 1:** (Norma de vetores e matrizes)
Sejam o vetor $v$ e a matriz $A$ dados. Vamos obter algumas normas. 

$$A=\left[\begin{array}{rrrr}
3 & 2 & 11 &-1 \\ 
1 & 5 & -1 & 0 \\ 
4 & 0 & 1 & 2 \\
0 & -2 & 7 & 10
\end{array}\right]
\quad \text{e} \quad
v = 
\left[\begin{array}{r} 
1 \\ 0 \\ 3\\-2
\end{array} \right]$$

In [68]:
import numpy as np
A = np.array([[3,2,11,-1],[1,5,-1,0],[4,0,1,2],[0,-2,7,10]])
v = np.array([1,0,3,-2])

- Norma coluna da matriz: $$\|\mathrm{A}\|_1=\|\mathrm{A}\|_C=\operatorname{máx}_{1 \leq j \leq n} \sum_{i=1}^n\left|a_{i j}\right|$$

In [69]:
np.max(np.sum(abs(A), axis=0))

20

ou, de forma equivalente,

In [70]:
np.linalg.norm(A, 1)

20.0

- Norma linha da matriz: $$\|\mathrm{A}\|_{\infty}=\|\mathrm{A}\|_L=\operatorname{máx}_{1 \leq i \leq n} \sum_{j=1}^n\left|a_{i j}\right| $$

In [71]:
# resolva aqui

- Norma euclidiana da matriz: $$\|\mathrm{A}\|_2=\sqrt{\sum_{i=1}^n \sum_{j=1}^n\left(a_{i j}\right)^2}$$

In [72]:
# resolva aqui

- Norma $l_p$ do vetor:
$$
\|x\|_p=\left(\sum_{i=1}^n\left|x_i\right|^p\right)^{1 / p} ; p \geq 1
$$

In [73]:
#norma Euclidiana: p=2
np.sum(abs(v)**2)**(1/2)

3.7416573867739413

ou 

In [74]:
np.linalg.norm(v)

3.7416573867739413

In [75]:
# calcule para p=1 e p>2

- Norma infinito do vetor:
$$
\|x\|_{\infty}=\operatorname{máx}\left\{\left|x_i\right|, i=1, \ldots, n\right\}
$$


In [76]:
# resolva aqui

#### Solução de um sistema por método iterativo
Para determinar a solução de um sistema linear por métodos iterativos, precisamos transformar o sistema dado em um outro sistema equivalente que estabeleça um processo iterativo. Suponha então, que o sistema $Ax = b$ seja reescrito na forma equivalente 

$$x = Hx + g$$

tal que a solução $\bar{x}$ de $x = Hx + g$ é  também, solução de $Ax = b$. A partir dessa nova forma podemos obter um processo iterativo que fornecerá a sequência de soluções aproximadas que buscamos. Assim, seja $x^{(0)}$ uma aproximação inicial para a solução $\bar{x}$, obtemos as aproximações sucessivas $x^{(k)}$ para a solução desejada usando o processo iterativo definido por:

$$x^{(k)} = Hx^{(k-1)} + g$$

Uma condição necessária e suficiente para a convergência do processo iterativo definido por $x = Hx + g$ é que $max \{ |\lambda_i |\} < 1$, onde $\lambda_i$ são os autovalores da matriz $H$. Como consequência dessa afirmação, o processo será convergente se para qualquer norma de matrizes, $\| H \| < 1$. A prova pode ser encontrada em  Franco (2006, p.169).

#### Exemplo 2: Autovalores e convergência
Consideremos a matriz $H = \bar{A}-I$, em que $\bar{A}$ é a matriz $A$ do exemplo 1 com cada linha dividida pelo elemento da diagonal principal. Então calculemos os autovalores e a norma euclidiana de $H$ .   


In [101]:
A = np.array([[3,2,11,-1],[1,5,-1,0],[4,0,1,2],[0,-2,7,10]])

Obtendo a matriz $H$:

In [107]:
H = A/np.diag(A).reshape(4,1)-np.eye(len(A))
print (H)

[[ 0.          0.66666667  3.66666667 -0.33333333]
 [ 0.2         0.         -0.2         0.        ]
 [ 4.          0.          0.          2.        ]
 [ 0.         -0.2         0.7         0.        ]]


Calculando os autovalores:

In [103]:
aut_val = np.linalg.eig(H)[0]
aut_val

array([ 3.97756454, -4.06272331,  0.22917206, -0.14401329])

O máximo em módulo é:

In [108]:
np.abs(aut_val).max()

4.062723307288213

Calculando a norma $p=2$ da matriz $H$:

In [106]:
np.linalg.norm(H,2)

4.485067478547747

Como é possível perceber, o Nesse caso,  valor, em módulo, dentre os autovalores de $H$ é maior que $1$ assim como a norma eulidiana de $H$. Neste caso, se quiséssemos usar um método iterativo para resolver o sistema $Ax=v$ e ter garantia de convergência, teríamos que fazer uma troca de linhas da mtriz $A$ de modo a obter um sistema equivalente em que a convergência do método iterativo para sua resolução é assegurada.

Observe que trocano a primeira e a terceira linha de $A$, obtemos uma matriz $H$ com norma menor que $1$.

In [111]:
A[[0,2]]=A[[2,0]]

In [131]:
H = A/np.diag(A).reshape(4,1)-np.eye(len(A))
np.linalg.norm(H)

5.883026432033091

**Exercícios:** 

**1.** Calcule outras normas para a matriz $H$.

In [134]:
# resolva aqui

**2.** Verifique se a matriz $A$ é estritamente diagonalmente dominante, ou seja,

$$ |a_{ii}| > \sum_{j=1,i\neq j} |a_{ij}| , i=1,...n \text{.}$$

É possível trocar linhas da matriz $A$ de modo que ela se torna estr?itamente diagonalmente dominante?

In [135]:
# resolva aqui

### Método iterativo de Jacobi-Richardson

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
             \end{cases} $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases} 
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\ 
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\ 
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\ 
\end{cases} $$

O método iterativo de Jacobi-Richardson fornece uma sequência de soluções $x^{(k)}=[x_1^{(k)}, x_2^{(k}), ..., x_n^{(k)}]$ com $k=1,2,3,...$ a partir de uma solução inicial $x^{(0)}=[x_1^{(0)}, x_2^{(0), ..., x_n^{(0)}}]$ dada por:

$$ \begin{cases} 
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k)} - \frac{a_{n2}}{a_{nn}}x_3^{(k)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k)} \\
\end{cases} $$


ou, ainda:

$$ x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j=1}^{i-1} a_{ij}x_j^{(k)} -\sum_{j=i+1}^{n} a_{ij}x_j^{(k)} \right) \,\,\,\,\,\, i=1,...,n$$

Na forma matricial, o método de Jacobi-Richardson pode ser escrito como:

$$ x^{(k+1)} = Hx^{(k)} + g $$

onde 


$$H = 
\left[\begin{array}{ccccc} 
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\ 
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\quad \text{e} \quad
g = 
\left[\begin{array}{c} 
\frac{b_1}{a_{11}} \\ 
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]$$


ou, ainda,


$$
\left[\begin{array}{c} 
x_1^{(k+1)} \\ 
x_2^{(k+1)} \\
\vdots \\
x_n^{(k+1)}\\
\end{array} \right]
= 
\left[\begin{array}{ccccc} 
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\ 
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\left[\begin{array}{c} 
x_1^{(k)} \\ 
x_2^{(k)} \\
\vdots \\
x_n^{(k)}\\
\end{array} \right]
+
\left[\begin{array}{c} 
\frac{b_1}{a_{11}} \\ 
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]
$$

#### Convergência
Podemos verificar a convergência do método avaliando a matriz $A$. Se a matriz $A=[a_{ij}]_{i,j=1.,,,,n}$ do sistema $Ax=b$ for estritamente diagonalmente dominante, ou seja,

$$ |a_{ii}| > \sum_{j=1,i\neq j} |a_{ij}| , i=1,...n$$

então, o método iterativo de Jacobi-Richardson será convergente. 

#### Critério de parada 
Considerando que o processo iterativo está fornecendo uma sequência convergente, um critério de parada para o algoritmo pode ser dado por

$$ \frac{\parallel x^n - x^{n-1}\parallel }{\parallel x^n\parallel} < \epsilon$$

para alguma norma vetorial $ \| \cdot \| : V \rightarrow R$ e alguma tolerância $\epsilon$ pré estabelecida. 

Por conveniência, é comum utilizarmos a norma infinito:

$$\parallel x\parallel _ \infty = max \{ |x_0|, |x_1|, ..., |x_n| \}$$

**Exemplo:**
Usando o método interativo de Jacobi-Richardson, determine uma solução aproximada para o seguinte sistema de equações lineares, com aproximação inicial $x^{(0)}=(0,0,0)^T$ e precisão $\epsilon = 0.01$. 

$$
\left[\begin{array}{ccc} 
10 & 2 & 1\\
1 & 5 & 1\\
2 & 3 & 10\\
\end{array} \right]
\left[\begin{array}{c} 
x_1\\
x_2\\
x_3\\
\end{array} \right]
=
\left[\begin{array}{c} 
14\\
11\\
8\\
\end{array} \right]
$$

Reescrevendo o sistema, obtemos:

$$ 
\begin{cases} 
x_1^{(k+1)} = \frac{14}{10} - \frac{2}{10}x_2^{(k)} - \frac{1}{10}x_3^{(k)}\\ 
x_2^{(k+1)} = \frac{11}{5} - \frac{1}{5}x_1^{(k)} - \frac{1}{5}x_3^{(k)}\\ 
x_3^{(k+1)} = \frac{8}{10} - \frac{2}{10}x_1^{(k)} - \frac{3}{10}x_2^{(k)}\\ 
\end{cases} 
$$

A partir da primeira iteração, $k=0$, $x^{(0)}=(x_1^{(0)},x_2^{(0)},x_3^{(0)})^T=(0,0,0)^T$obtem-se:

$x_1^{(1)}=\frac{14}{10}-\frac{2}{10}x_2^{(0)}-\frac{1}{10}x_3^{(0)}=\frac{14}{10}-\frac{2}{10}(0)-\frac{1}{10}(0)=1.4$


$x_2^{(1)}= frac{11}{5}-\frac{1}{5}x_1^{(0)}-\frac{1}{5}x_3^{(0)}= \frac{11}{5}-\frac{1}{5}(0)-\frac{1}{5}(0)=0.22$


$x_3^{(1)}=\frac{8}{10}-\frac{2}{10}x_1^{(0)}-\frac{3}{10}x_2^{(0)}=\frac{8}{10}-\frac{2}{10}(0)-\frac{3}{10}(0)=0.8$

Em python podemos fazer como é mostrado a seguir

In [145]:
# Dados iniciais
x = np.array([0.,0.,0.])

A =  np.array([[10.,2.,1.],[1.,5.,1.],[2.,3.,10.]])
b = np.array([14.,11.,8.])

In [146]:
# função para fazer as iterações
def itera(x):
    x1 = (b[0] - A[0,1]*x[1] - A[0,2]*x[2])/A[0,0]
    x2 = (b[1] - A[1,0]*x[0] - A[1,2]*x[2])/A[1,1]
    x3 = (b[2] - A[2,0]*x[0] - A[2,1]*x[1])/A[2,2]
    x = np.array([x1, x2, x3])
    return x

In [147]:
x = itera(x)
x

array([1.4, 2.2, 0.8])

In [148]:
#várias iterações e o erro
x = np.array([0.,0.,0.])

x_ant = x
for i in range(2,8):
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x
    print (i, x, np.round(err,4))
    
print ("Solução:", np.round(x,4))

2 [1.4 2.2 0.8] 1.0
3 [ 0.88  1.76 -0.14] 0.5341
4 [1.062 2.052 0.096] 0.1423
5 [ 0.98    1.9684 -0.028 ] 0.063
6 [1.00912 2.0096  0.01348] 0.0206
7 [ 0.996732  1.99548  -0.004704] 0.0091
Solução: [ 0.9967  1.9955 -0.0047]


Resolvendo novamente, mas agora usando operações matriciais

In [149]:
#Calculando a matriz H
H = A.copy()
g = b.copy()

for i in range(len(A)):
    H[i] = -A[i]/A[i,i]
    g[i] = b[i]/A[i,i]
    
H = H + np.identity(len(A))
print ('H =', H)
print ('g =', g)

H = [[ 0.  -0.2 -0.1]
 [-0.2  0.  -0.2]
 [-0.2 -0.3  0. ]]
g = [1.4 2.2 0.8]


In [150]:
#ou, alternativamente
H = np.eye(len(A))- A/np.diag(A).reshape(3,1)
print ('H =', H)

H = [[ 0.  -0.2 -0.1]
 [-0.2  0.  -0.2]
 [-0.2 -0.3  0. ]]


In [151]:
g = b/np.diag(A)
print ('g =', g)

g = [1.4 2.2 0.8]


In [152]:
# verificando a convergẽncia com a norma inf 
norma_inf = np.sum(abs(H), axis=1).max()
print ('Norma:', norma_inf)

Norma: 0.5


In [153]:
x = np.array([0,0,0])

In [154]:
x = H@x+g
x

array([1.4, 2.2, 0.8])

In [155]:
# fazendo as iterações
err = 1
x = np.array([0,0,0])
x_ant = x

print ('Iterações:')
while err>0.01:
    x = np.dot(H,x)+g
    err = abs(max(x-x_ant)/max(x))
    x_ant = x   
    print(np.round(x, 4), ", Err=", np.round(err,5))

Iterações:
[1.4 2.2 0.8] , Err= 1.0
[ 0.88  1.76 -0.14] , Err= 0.25
[1.062 2.052 0.096] , Err= 0.1423
[ 0.98    1.9684 -0.028 ] , Err= 0.04166
[1.0091 2.0096 0.0135] , Err= 0.02064
[ 0.9967  1.9955 -0.0047] , Err= 0.00621


### Método iterativo de Gaus-Seidel

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
             \end{cases} $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases} 
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\ 
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\ 
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\ 
\end{cases} $$

O método iterativo de Gauss-Seidel é dado da seguinte forma:

$$ \begin{cases} 
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k+1)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\ 
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k+1)} - \frac{a_{n2}}{a_{nn}}x_3^{(k+1)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k+1)} \\
\end{cases} $$


De forma geral, o método de Gauss-Seidel pode ser resumido como:

$$ x_i^{(k+1)} = \frac{1}{a_{ii}} \left(b_i - \sum_{j=1}^{i-1} a_{ij}x_j^{(k+1)} -\sum_{j=i+1}^{n} a_{ij}x_j^{(k)} \right) \,\,\,\,\,\, i=1,...,n$$

ou ainda, de forma equivalente:

$$ x_i^{(k+1)} = g_i - \sum_{j=1}^{i-1} h_{ij}x_j^{(k+1)} -\sum_{j=i+1}^{n} h_{ij}x_j^{(k)} \,\,\,\,\,\, i=1,...,n$$

em que $g_i=\frac{b_i}{a_{ii}}$ e $h_{ij}=\frac{a_{ij}}{a_{ii}}$, $i=1,...,n$. 

#### Convergência: critério de Sassenfield
Sejam as constantes $\beta_i$ definidas pelas seguintes fórmulas de recorrência:

$$\beta_i = \sum_{j=1}^{i-1} |h_{ij}|\beta_i +\sum_{j=i+1}^{n} |h_{ij}| \,\,\,\,\,\, i=1,...,n$$

e seja

$$\beta = \max_{1 \leq i \leq n}\ \beta_i$$

Então, se $\beta < 1$, a sequência $x^{(k)}$, gerada pelo método iterativo de Gauss-Seidel, converge para a solução $x$ do sistema dado.

**Exemplo:** Usando o método iterativo de Gauss-Seidel, determine uma solução aproximada para o sistema dado a seguir, com aproximação inicial
$x^{(0)} =(x_1^{(0)},x_2^{(0)},x_3^{(0)})^t =(0,0,0)^t$ e precisão $\epsilon = 0.01$.

$$ \left[\begin{array}{ccc} 
10 & 2 & 1\\ 1 & 5 & 1\\ 2 & 3 & 10\\
\end{array} \right]
\left[\begin{array}{c} 
x_1\\ x_2\\ x_3\\
\end{array} \right]
=
\left[\begin{array}{c} 
14\\ 11\\ 8\\
\end{array} \right] $$

In [156]:
# Entrando com a matriz a e o vetor b
A = np.array([[10.0, 2.0, 1.0],
              [ 1.0, 5.0, 1.0],
              [ 2.0, 3.0, 10.0]])

b = np.array([14., 11., 8.])

Uma implementação é apresentada a seguir:

In [157]:
from numpy.linalg import inv

In [158]:
n = len(A)
P = np.zeros((n,n))
Q = np.zeros((n,n))
g = np.zeros(n)

x = np.array([0.,0.,0.])
for i in range(n):
    P[i,0:i] = -A[i,0:i]/A[i,i]
    Q[i,i+1:n] = -A[i,i+1:n]/A[i,i]
    g[i] = b[i]/A[i,i] 
    
I = np.eye(n)
H = np.dot(inv(I-P),Q)
g = np.dot(inv(I-P),g)


for k in range(4):
    x = np.dot(H,x) + g
    
    print (np.round(x,4))

[ 1.4    1.92  -0.056]
[ 1.0216  2.0069 -0.0064]
[ 9.9930e-01  2.0014e+00 -3.0000e-04]
[0.9997 2.0001 0.    ]


Uma solução alternativa


In [159]:
# obtendo a matriz H
H = np.eye(len(A))-(A.T/np.diag(A)).T

print ('Matriz H:')
print(H)

Matriz H:
[[ 0.  -0.2 -0.1]
 [-0.2  0.  -0.2]
 [-0.2 -0.3  0. ]]


In [160]:
# verificando a convergência 
beta = []
for i in range(len(H)):
    bi = np.dot(beta,abs(H[i,0:i]))+ np.sum(abs(H[i,i+1:]))
    beta.append(np.round(bi,4))

print('Convergência:')
print ('max{',beta,'} =',np.array(beta).max())

Convergência:
max{ [0.3, 0.26, 0.138] } = 0.3


In [161]:
n = len(A)
x = np.array([0.,0.,0.])

for k in range(1,5):
    for i in range(len(A)):
        x[i] = (b[i] - np.dot(A[i,0:i],x[0:i])-np.dot(A[i,i+1:n],x[i+1:n]))/A[i,i]
    print(k, np.round(x,4))

print("Solução:",np.round(x,4))

1 [ 1.4    1.92  -0.056]
2 [ 1.0216  2.0069 -0.0064]
3 [ 9.9930e-01  2.0014e+00 -3.0000e-04]
4 [0.9997 2.0001 0.    ]
Solução: [0.9997 2.0001 0.    ]


___
Na forma matricial, o método de Gauss-Seidel  pode ser escrito como

$$\left[
    \begin{array}{c} 
	         x_1^{(k+1)} \\ 
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array} 
\right]
=
\left[\begin{array}{ccccc} 
	         0                     & 0 & 0 & \cdots & 0 \\ 
	         -\frac{a_{21}}{a_{22}} & 0 & 0 & \cdots & 0 \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & \cdots & -\frac{a_{n \,n-1}}{a_{nn}} & 0\\
	         \end{array} \right]
             \left[
    \begin{array}{c} 
	         x_1^{(k+1)} \\ 
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array} 
\right]
+
\left[\begin{array}{ccccc} 
	         0&  -\frac{a_{12}}{a_{11}}& -\frac{a_{13}}{a_{11}}& \cdots &-\frac{a_{1n}}{a_{11}} \\ 
	         0& 0& -\frac{a_{23}}{a_{22}} & \cdots & -\frac{a_{2n}}{a_{22}} \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         0& 0& 0& \cdots& 0\\
	         \end{array} \right]
\left[\begin{array}{c} 
	         x_1^{(k)} \\ 
	         x_2^{(k)} \\
             \vdots\\
	         x_n^{(k)} \\
	\end{array} \right]
+
\left[ \begin{array}{c} 
	         \frac{b_1}{a_{11}} \\ 
	         \frac{b_2}{a_{22}} \\
             \vdots\\
	         \frac{b_n}{a_{nn}} \\
	\end{array} \right]$$


ou 
$$ x^{(k+1)} = P x^{(k+1)} + Q x^{(k)} + g$$

$$ (I-P)x^{(k+1)} = Q x^{(k)} + g$$

$$ x^{(k+1)} = (I-P)^{-1}Q x^{(k)} + (I-P)^{-1}g$$

Fazendo-se $H = (I-P)^{-1}Q$ e $g' =(I-P)^{-1}g$ o processo iterativo torna-se

$$x^{(k+1)} = H x^{(k)} + g'$$

In [162]:
from numpy.linalg import inv


x = np.array([0.,0.,0.])

eps = 0.001
# Entrando com a matriz a e o vetor b
A = np.array([[10.0, 2.0, 1.0],
              [ 1.0, 5.0, 1.0],
              [ 2.0, 3.0, 10.0]])

b = np.array([14., 11., 8.])

n = len(A)
P = np.zeros((n,n))
Q = np.zeros((n,n))
g = np.zeros(n)


for i in range(n):
    P[i,0:i] = -A[i,0:i]/A[i,i]
    Q[i,i+1:n] = -A[i,i+1:n]/A[i,i]
    g[i] = b[i]/A[i,i] 
    
I = np.eye(n)
H = np.dot(inv(I-P),Q)
g = np.dot(inv(I-P),g)


for k in range(4):
    x = np.dot(H,x) + g
    
    print (np.round(x,4))

[ 1.4    1.92  -0.056]
[ 1.0216  2.0069 -0.0064]
[ 9.9930e-01  2.0014e+00 -3.0000e-04]
[0.9997 2.0001 0.    ]


Ou, de um modo mais esperto...

In [163]:
P = np.tril(H)
P

array([[0.   , 0.   , 0.   ],
       [0.   , 0.04 , 0.   ],
       [0.   , 0.028, 0.074]])

In [164]:
Q = np.triu(H)
Q

array([[ 0.   , -0.2  , -0.1  ],
       [ 0.   ,  0.04 , -0.18 ],
       [ 0.   ,  0.   ,  0.074]])

In [165]:
Hl = np.linalg.inv(np.eye(len(H))-P)@Q
gl = np.linalg.inv(np.eye(len(H))-P)@g

In [166]:
# fazendo as iterações
err = 1
x = np.array([0,0,0])
x_ant = x

print ('Iterações:')
while err>0.001:
    x = (Hl@x)+gl
    err = abs(max(x-x_ant)/max(x))
    x_ant = x   
    print(np.round(x, 4), ", Err=", np.round(err,5))

Iterações:
[1.4 2.  0. ] , Err= 1.0
[1.     2.0833 0.0025] , Err= 0.04
[0.9831 2.0863 0.0028] , Err= 0.00144
[0.9825 2.0864 0.0028] , Err= 3e-05


### Exercícios 

**1.** Usando o método iterativo de Gauss-Seidel, determine uma solução aproximada para o sistema dado a seguir, com aproximação inicial
$x^{(0)} =(0,0,0,0,0)^t$ e 10 iterações.

$$ \left[\begin{array}{ccccc} 
5 & 1 & 2 & 1 & -1\\ 
0&6&1&1&-1\\ 
0&1&-3&2&1\\
3&0&2&7&0\\
1&1&0&0&8\\
\end{array} \right]
\left[\begin{array}{c} 
x_1\\ x_2\\ x_3\\x_4\\x_5\\
\end{array} \right]
=
\left[\begin{array}{c} 
1\\ 2\\ 0\\2\\1\\
\end{array} \right] $$